/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import GUI.FormInventarisKeluar;
import Koneksi.koneksi;
/**
 *
 * @author ITAdmin
 */
public class FormPopupInventoriMasuk extends javax.swing.JFrame {
    // Mendeklarasikan dan menginisialisasi koneksi ke database menggunakan objek dari kelas koneksi
    private Connection conn = new koneksi().connect();

    // Mendeklarasikan objek model tabel default untuk digunakan dalam tampilan dan manipulasi data dalam tabel
    private DefaultTableModel tabmode;

    // Mendeklarasikan objek invmsk yang terkait dengan objek dari kelas FormInventarisKeluar
    public FormInventarisKeluar invmsk = null;

    /**
     * Creates new form PopupInventoriMasuk
     */
    public FormPopupInventoriMasuk() {
        initComponents();
        // Memanggil metode datatable() untuk menampilkan data inventaris masuk saat program dimulai atau suatu event tertentu terjadi
        datatable();
        }
        // Metode untuk menampilkan data inventaris masuk dalam tabel
        private void datatable() {
        // Menentukan kolom yang akan ditampilkan dalam tabel
        Object[] Baris = {"ID Inventori Masuk", "Kode barang", "Nama Barang", "Kategori", "Merek", "Ukuran", "Kode Lokasi", "Nama Lokasi"};
    
        // Membuat model tabel (tabmode) dengan kolom yang telah ditentukan
        tabmode = new DefaultTableModel(null, Baris);
    
        // Mendapatkan teks dari field pencarian
        String cariitem = Cari.getText();
    
    try {
                // Membuat query SQL untuk mengambil data inventaris masuk berdasarkan kriteria pencarian
                String sql = "SELECT a.kd_inventaris_masuk, b.kd_barang, b.nama_barang, b.kategori_barang, b.merek, b.ukuran"
                + ", c.kd_lokasi, c.nama_lokasi FROM trx_inventaris_masuk a JOIN mst_barang b ON a.kd_barang=b.kd_barang"
                + " LEFT JOIN mst_lokasi c ON a.kd_lokasi=c.kd_lokasi WHERE a.kd_inventaris_masuk LIKE '%"+cariitem+"%' "
                + " OR b.kd_barang LIKE '%"+cariitem+"%' OR b.nama_barang LIKE '%"+cariitem+"%' ORDER BY kd_inventaris_masuk ASC";
        
        // Membuat objek Statement untuk menjalankan query SQL
        Statement stat = conn.createStatement();
        
        // Mengeksekusi query SQL dan mendapatkan hasil
        ResultSet hasil = stat.executeQuery(sql);
        
        // Mengisi model tabel dengan data hasil query
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8)
            });
        }
        
        // Menetapkan model tabel ke komponen tabel (TabelInventoryMasuk) pada antarmuka pengguna
        TabelInventoryMasuk.setModel(tabmode);
    } catch (Exception e) {
        // Menampilkan pesan kesalahan jika terjadi exception saat menjalankan query SQL
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil" + e);
    }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelInventoryMasuk = new javax.swing.JTable();
        Cari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 255, 102));

        TabelInventoryMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelInventoryMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelInventoryMasukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelInventoryMasuk);

        Cari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CariKeyPressed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/CARI.png"))); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/KELUAR.png"))); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelInventoryMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelInventoryMasukMouseClicked
      // Mendapatkan indeks baris yang dipilih dalam tabel TabelInventoryMasuk
       int index = TabelInventoryMasuk.getSelectedRow();

      // Menetapkan nilai dari kolom-kolom terpilih ke variabel-variabel pada objek invmsk
        invmsk.idinvmsk = TabelInventoryMasuk.getValueAt(index, 0).toString();
        invmsk.kdbrg = TabelInventoryMasuk.getValueAt(index, 1).toString();
        invmsk.nmbrg = TabelInventoryMasuk.getValueAt(index, 2).toString();
        invmsk.ktgbrg = TabelInventoryMasuk.getValueAt(index, 3).toString();
        invmsk.mrk = TabelInventoryMasuk.getValueAt(index, 4).toString();
        invmsk.uk = TabelInventoryMasuk.getValueAt(index, 5).toString();
        invmsk.kdlok = TabelInventoryMasuk.getValueAt(index, 6).toString();
        invmsk.nmlok = TabelInventoryMasuk.getValueAt(index, 7).toString();

     // Memanggil metode invMasukTerpilih() pada objek invmsk
        invmsk.InventoryMasukTerpilih();

    // Menutup jendela saat ini
    this.dispose();

    }//GEN-LAST:event_TabelInventoryMasukMouseClicked

    private void CariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CariKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_CariKeyPressed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        datatable();
    }//GEN-LAST:event_btncariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPopupInventoriMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPopupInventoriMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPopupInventoriMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPopupInventoriMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPopupInventoriMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cari;
    private javax.swing.JTable TabelInventoryMasuk;
    private javax.swing.JButton btncari;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
