/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import Koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class FormMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
        //Membuat Frame Layar penuh pada Form Menu Utama
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        databarang = new javax.swing.JMenuItem();
        datalokasi = new javax.swing.JMenuItem();
        Datapengguna = new javax.swing.JMenuItem();
        InventoryBarang = new javax.swing.JMenu();
        InventoryKeluar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/inventory-management-8088360-6501983.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-close-30.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(kGradientPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 204));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-menu-30 (1).png"))); // NOI18N
        Menu.setText("MENU");
        Menu.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N

        databarang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        databarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MenuDataBarang.png"))); // NOI18N
        databarang.setText("DATA BARANG");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        Menu.add(databarang);

        datalokasi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        datalokasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MenuDataLokasi.png"))); // NOI18N
        datalokasi.setText("DATA LOKASI");
        datalokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datalokasiActionPerformed(evt);
            }
        });
        Menu.add(datalokasi);

        Datapengguna.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Datapengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MenuDataUser.png"))); // NOI18N
        Datapengguna.setText("DATA ADMIN");
        Datapengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatapenggunaActionPerformed(evt);
            }
        });
        Menu.add(Datapengguna);

        jMenuBar1.add(Menu);

        InventoryBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconsinventory.png"))); // NOI18N
        InventoryBarang.setText("INVENTORY BARANG");
        InventoryBarang.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N

        InventoryKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MenuInventoryMasuk.png"))); // NOI18N
        InventoryKeluar.setText("INVENTORY MASUK");
        InventoryKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryKeluarActionPerformed(evt);
            }
        });
        InventoryBarang.add(InventoryKeluar);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MenuInventoryKeluar.png"))); // NOI18N
        jMenuItem2.setText("INVENTORY KELUAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        InventoryBarang.add(jMenuItem2);

        jMenuBar1.add(InventoryBarang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InventoryKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryKeluarActionPerformed
        // Memanggil Form Inventaris Masuk ketika Icon Inventaris Masuk di Klik
         FormInventarisMasuk frmL = new FormInventarisMasuk();
         frmL.setVisible(true);
    }//GEN-LAST:event_InventoryKeluarActionPerformed

    private void datalokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datalokasiActionPerformed
        // Memanggil Form Lokasi ketika icon DATA LOKASI di Klik
        FormLokasi frmL = new FormLokasi();
        frmL.setVisible(true);
    }//GEN-LAST:event_datalokasiActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // Memanggil Form Data Barang ketika Icon DATA BARANG DI klik
       FormDataBarang frml = new FormDataBarang();
       frml.setVisible(true);
    }//GEN-LAST:event_databarangActionPerformed

    private void DatapenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatapenggunaActionPerformed
        
        //Memanggil Form Admin ketika Icon DATA ADMIN di klik
        FormUser frmB = new FormUser();
        frmB.setVisible(true);
    }//GEN-LAST:event_DatapenggunaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Memanggil Form Inventaris Keluar ketika Icon Inventory Keluar di Klik
        FormInventarisKeluar frmB = new FormInventarisKeluar();
        frmB.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       //Memanggil Form Login ketika Icon CLOSE di Klik
        FormLogin frmB = new FormLogin();
        frmB.setVisible(true);
        
        // Menutup form menu utama
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Datapengguna;
    private javax.swing.JMenu InventoryBarang;
    private javax.swing.JMenuItem InventoryKeluar;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datalokasi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
